### ISSUE TITLE
조장님 저희 문단 나눌까요?

### ISSUE THREAD

**Issue by shumnee** [CAU-DOSC/TransSum08#1]
다음 주 목요일까지던데 문단 나눠요~

**Comment by shumnee** [comment]
저희조가 몇 명인지 모르겠지만 토요일까지 확인 안하시면 제가 첫 부분 번역 시작할게요!

**Comment by KwonWon** [comment]
나눌게요 잠시만용

**Comment by KwonWon** [comment]
8조 되면서 Open Source Paradigm이니까
18페이지고 4명이니까
4페이지씩 끊어서 권원/배용한/변영무/허수민 씨 이렇게 진행하죠
남은 2페이지에 대해서는 다시 합치구요
